---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/carts":
    get:
      summary: Get current cart
      tags:
      - Carts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    id: 2424
                    products: []
                    total_price: 0.0
    post:
      summary: Create cart
      tags:
      - Carts
      parameters: []
      responses:
        '201':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    id: 2428
                    products:
                    - id: 1376
                      name: Test Product
                      quantity: 2
                      unit_price: 10.0
                      total_price: 20.0
                    total_price: 20.0
        '404':
          description: Product not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    error: Resource not found.
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/carts/requests/create"
  "/carts/add_item":
    post:
      summary: Add quantity to existing item
      tags:
      - Carts
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    id: 2433
                    products:
                    - id: 1379
                      name: Test Product
                      quantity: 2
                      unit_price: 10.0
                      total_price: 20.0
                    total_price: 20.0
        '404':
          description: Product not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    error: Resource not found.
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/carts/requests/add_item"
  "/carts/{product_id}":
    parameters:
    - name: product_id
      in: path
      required: true
      schema:
        type: string
    delete:
      summary: Remove item from cart
      tags:
      - Carts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    id: 2438
                    products: []
                    total_price: 0.0
        '404':
          description: Item not found in cart
          content:
            application/json:
              examples:
                Default:
                  value:
                    error: Produto n√£o encontrado no carrinho.
  "/products":
    get:
      summary: List all products
      tags:
      - Products
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                  - id: 1389
                    name: Test Product
                    price: '10.0'
                    created_at: '2025-09-05T03:00:40.515Z'
                    updated_at: '2025-09-05T03:00:40.515Z'
                  - id: 1390
                    name: Test Product
                    price: '10.0'
                    created_at: '2025-09-05T03:00:40.517Z'
                    updated_at: '2025-09-05T03:00:40.517Z'
                  - id: 1391
                    name: Test Product
                    price: '10.0'
                    created_at: '2025-09-05T03:00:40.519Z'
                    updated_at: '2025-09-05T03:00:40.519Z'
              schema:
                "$ref": "#/components/schemas/v1/products/responses/index"
    post:
      summary: Create a new product
      tags:
      - Products
      parameters: []
      responses:
        '201':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    id: 1394
                    name: New Product
                    price: '15.99'
                    created_at: '2025-09-05T03:00:40.542Z'
                    updated_at: '2025-09-05T03:00:40.542Z'
              schema:
                "$ref": "#/components/schemas/v1/products/responses/create"
        '422':
          description: Validation errors
          content:
            application/json:
              examples:
                Default:
                  value:
                    name:
                    - can't be blank
                    price:
                    - must be greater than or equal to 0
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/products/requests/create"
  "/products/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Show product
      tags:
      - Products
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    id: 1396
                    name: Test Product
                    price: '20.0'
                    created_at: '2025-09-05T03:00:40.559Z'
                    updated_at: '2025-09-05T03:00:40.559Z'
              schema:
                "$ref": "#/components/schemas/v1/products/responses/show"
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    error: Resource not found.
    patch:
      summary: Update product
      tags:
      - Products
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                Default:
                  value:
                    name: Updated Product
                    price: '15.0'
                    id: 1399
                    created_at: '2025-09-05T03:00:40.592Z'
                    updated_at: '2025-09-05T03:00:40.597Z'
              schema:
                "$ref": "#/components/schemas/v1/products/responses/update"
        '422':
          description: Validation errors
          content:
            application/json:
              examples:
                Default:
                  value:
                    name:
                    - can't be blank
                    price:
                    - must be greater than or equal to 0
        '404':
          description: Not found
          content:
            application/json:
              examples:
                Default:
                  value:
                    error: Resource not found.
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/v1/products/requests/update"
    delete:
      summary: Delete product
      tags:
      - Products
      responses:
        '204':
          description: Successful
        '404':
          description: Not found
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
  schemas:
    _common:
      Error:
        type: object
        properties:
          errors:
            type: object
            additionalProperties:
              type: array
              items:
                type: string
      Pagination:
        type: object
        properties:
          current_page:
            type: integer
          total_pages:
            type: integer
          total_count:
            type: integer
          per_page:
            type: integer
    _private:
      User:
        type: object
        properties:
          id:
            type: integer
          email:
            type: string
          created_at:
            type: string
            format: date-time
          updated_at:
            type: string
            format: date-time
    v1:
      carts:
        _common:
          title: Cart
          type: object
          additionalProperties: true
          properties:
            id:
              type: integer
            total_price:
              type: number
              format: decimal
            products:
              type: array
              items:
                "$ref": "#/components/schemas/v1/carts/_product"
        _product:
          title: Product in Cart
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            quantity:
              type: integer
            unit_price:
              type: number
              format: decimal
            total_price:
              type: number
              format: decimal
        requests:
          add_item:
            title: Add Item to Cart Request
            type: object
            properties:
              cart:
                type: object
                properties:
                  product_id:
                    type: integer
                  quantity:
                    type: integer
                required:
                - product_id
                - quantity
            required:
            - cart
          create:
            title: Create Cart Request
            type: object
            properties:
              cart:
                type: object
                properties:
                  product_id:
                    type: integer
                  quantity:
                    type: integer
                required:
                - product_id
                - quantity
            required:
            - cart
          update:
            update:
              type: object
              properties:
                cart:
                  type: object
                  properties:
                    product_id:
                      type: integer
                    quantity:
                      type: integer
                  required:
                  - product_id
                  - quantity
              required:
              - cart
        responses:
          add_item:
            title: Add Item to Cart Response
            "$ref": "#/components/schemas/v1/carts/_common"
          create:
            title: Create Cart Response
            "$ref": "#/components/schemas/v1/carts/_common"
          remove_item:
            title: Remove Item from Cart Response
            "$ref": "#/components/schemas/v1/carts/_common"
          show:
            title: Show Cart Response
            "$ref": "#/components/schemas/v1/carts/_common"
      products:
        _common:
          title: Product
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            price:
              type: string
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time
        requests:
          create:
            title: Create Product Request
            type: object
            properties:
              product:
                type: object
                properties:
                  name:
                    type: string
                  price:
                    type: number
                    format: decimal
                required:
                - name
                - price
            required:
            - product
          update:
            title: Update Product Request
            type: object
            properties:
              product:
                type: object
                properties:
                  name:
                    type: string
                  price:
                    type: number
                    format: decimal
            required:
            - product
        responses:
          create:
            title: Create Product Response
            "$ref": "#/components/schemas/v1/products/_common"
          index:
            title: Index Products Response
            type: array
            items:
              "$ref": "#/components/schemas/v1/products/_common"
          show:
            title: Show Product Response
            "$ref": "#/components/schemas/v1/products/_common"
          update:
            title: Update Product Response
            "$ref": "#/components/schemas/v1/products/_common"
servers:
- url: http://localhost:3000
